### ISSUE TITLE
Crash when clicking on comment multiple times

### ISSUE THREAD

**Issue by ghost** [android/plaid#238]
Occurred while trying to expand/collapse comment.
Activity: DribbbleShot.class 
Steps:
1. Expand/collapse some comment 
2. scroll 
3. Fast click multiple times on another

`12-20 17:17:16.413 13997-13997/io.plaidapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: io.plaidapp, PID: 13997
                                                             java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                                 at android.view.ViewGroup.addViewInner(ViewGroup.java:4919)
                                                                 at android.view.ViewGroup.addView(ViewGroup.java:4750)
                                                                 at android.view.ViewGroup.addView(ViewGroup.java:4690)
                                                                 at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:754)
                                                                 at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
                                                                 at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8029)
                                                                 at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7987)
                                                                 at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7975)
                                                                 at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1572)
                                                                 at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                                 at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                                 at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3670)
                                                                 at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3434)
                                                                 at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
                                                                 at android.view.View.layout(View.java:19678)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:6057)
                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                 at android.view.View.layout(View.java:19678)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:6057)
                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                 at android.view.View.layout(View.java:19678)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:6057)
                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                 at android.view.View.layout(View.java:19678)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:6057)
                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                 at com.android.internal.policy.DecorView.onLayout(DecorView.java:758)
                                                                 at android.view.View.layout(View.java:19678)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:6057)
                                                                 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2510)
                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2219)
                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1405)
                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6829)
                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:778)
                                                                 at android.view.Choreographer.doFrame(Choreographer.java:713)
                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
                                                                 at android.os.Handler.handleCallback(Handler.java:789)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                 at android.os.Looper.loop(Looper.java:164)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by keyboardsurfer** [comment]
Can't reproduce on current master.
