### ISSUE TITLE
Upgrading to 1.0.8 crash on launch

### ISSUE THREAD

**Issue by nickbutcher** [android/plaid#611]
```
2019-01-25 10:22:16.653 4854-4854/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.plaidapp, PID: 4854
    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.plaidapp/io.plaidapp.ui.HomeActivity}: java.util.ConcurrentModificationException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
        at io.plaidapp.core.data.prefs.SourcesRepository.getSources(SourcesRepository.kt:133)
        at io.plaidapp.core.data.DataManager.setupPageIndexes(DataManager.java:145)
        at io.plaidapp.core.data.DataManager.<init>(DataManager.java:71)
        at io.plaidapp.core.dagger.DataManagerModule.getDataManager(DataManagerModule.kt:85)
        at io.plaidapp.core.dagger.DataManagerModule.provideDataManager(DataManagerModule.kt:48)
        at io.plaidapp.core.dagger.DataManagerModule_ProvideDataManagerFactory.proxyProvideDataManager(DataManagerModule_ProvideDataManagerFactory.java:106)
        at io.plaidapp.dagger.DaggerHomeComponent.getDataManager(DaggerHomeComponent.java:199)
        at io.plaidapp.dagger.DaggerHomeComponent.injectHomeActivity(DaggerHomeComponent.java:266)
        at io.plaidapp.dagger.DaggerHomeComponent.inject(DaggerHomeComponent.java:262)
        at io.plaidapp.dagger.DaggerHomeComponent.inject(DaggerHomeComponent.java:63)
        at io.plaidapp.dagger.Injector.inject(Injector.kt:44)
        at io.plaidapp.ui.HomeActivity.onCreate(HomeActivity.java:140)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by ataulm** [comment]
Where's 1.0.8 from? `master` is on 1.0.7 still and `SourcesRepository` is only 132 lines long.

**Comment by ataulm** [comment]
Is it based on specific branch where `SourcesRepository` is different or is the stacktrace telling pork pies (reference to a crash on L133)?

**Comment by LoveqLRC** [comment]
same issues

**Comment by keyboardsurfer** [comment]
We're at 1.10. Closing as this seems stale.
