### ISSUE TITLE
"HomeActivity" crash after the refactor to Kotlin (2f341ad)

### ISSUE THREAD

**Issue by subhasha1** [android/plaid#711]
With the new commit converting `HomeActivity.java` to `HomeActivity.kt` , assignment of `HomeActivity.layoutManager` to `HomeActivity.grid` was missed which caused the following crash.
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.plaidapp/io.plaidapp.ui.HomeActivity}: kotlin.TypeCastException: null cannot be cast to non-null type androidx.recyclerview.widget.GridLayoutManager
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:81)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1935)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7116)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
     Caused by: kotlin.TypeCastException: null cannot be cast to non-null type androidx.recyclerview.widget.GridLayoutManager
        at io.plaidapp.ui.HomeActivity.setupGrid(HomeActivity.kt:393)
        at io.plaidapp.ui.HomeActivity.onCreate(HomeActivity.kt:290)
        at android.app.Activity.performCreate(Activity.java:7698)
        at android.app.Activity.performCreate(Activity.java:7687)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3096)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:81) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1935) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7116) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925) 
```

**Comment by kurtisnelson** [comment]
+1, seeing this on the latest Q emulator.
