### ISSUE TITLE
getting the crash when open the module  

### ISSUE THREAD

**Issue by gowthami77** [android/plaid#724]
Hi ,
I am getting the crash while opening the module from the app. I was uploaded the .aab file into play store. I run the app downloaded from the play store.  some times the module was opening after uninstall and reinstall the app then the module get crash some times.

PLease help me to resolve this issue. I struck over this.

I got this crash report in the logcat.

 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.testDynamic, PID: 5047
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.testDynamic/com.testDynamic.module.NumberFacts}: java.lang.ClassNotFoundException: Didn't find class "com.testDynamic.module.NumberFacts" on path: DexPathList[[zip file "/data/app/com.testDynamic-1/base.apk", zip file "/data/app/com.testDynamic-1/split_config.en.apk", zip file "/data/app/com.testDynamic-1/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.testDynamic-1/lib/arm64, /system/lib64, /vendor/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2626)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6342)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.testDynamic.module.NumberFacts" on path: DexPathList[[zip file "/data/app/com.testDynamic-1/base.apk", zip file "/data/app/com.testDynamic-1/split_config.en.apk", zip file "/data/app/com.testDynamic-1/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.testDynamic-1/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2616)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6342) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.testDynamic-1/split_config.en.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:373)
        at dalvik.system.DexFile.<init>(DexFile.java:113)
        at dalvik.system.DexFile.<init>(DexFile.java:78)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:359)
        at dalvik.system.DexPathList.makeElements(DexPathList.java:323)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:263)
        at dalvik.system.DexPathList.<init>(DexPathList.java:126)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:58)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:522)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:555)
        at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1925)
        at android.app.LoadedApk.getResources(LoadedApk.java:768)
        at android.app.ContextImpl.<init>(ContextImpl.java:2078)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2023)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5393)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1602)
        		... 6 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.testDynamic-1/split_config.xxhdpi.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:373)
        at dalvik.system.DexFile.<init>(DexFile.java:113)
        at dalvik.system.DexFile.<init>(DexFile.java:78)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:359)
        at dalvik.system.DexPathList.makeElements(DexPathList.java:323)
2019-06-13 12:24:23.493 5047-5047/? E/AndroidRuntime:     at dalvik.system.DexPathList.makeDexElements(DexPathList.java:263)
        at dalvik.system.DexPathList.<init>(DexPathList.java:126)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:58)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:522)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:555)
        at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1925)
        at android.app.LoadedApk.getResources(LoadedApk.java:768)
        at android.app.ContextImpl.<init>(ContextImpl.java:2078)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2023)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5393)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1602)

**Comment by nickbutcher** [comment]
This doesn't look like an issue with Plaid?! `com.testDynamic.module.NumberFacts`
