### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by jhwsx** [android/plaid#772]
```text
2019-10-11 20:23:16.734 20673-21004/io.plaidapp E/AndroidRuntime: FATAL EXCEPTION: IntentService[UpvoteStoryService]
    Process: io.plaidapp, PID: 20673
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean io.plaidapp.core.designernews.data.login.LoginRepository.isLoggedIn()' on a null object reference
        at io.plaidapp.core.designernews.data.votes.UpvoteStoryService.handleActionUpvote(UpvoteStoryService.java:72)
        at io.plaidapp.core.designernews.data.votes.UpvoteStoryService.onHandleIntent(UpvoteStoryService.java:64)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.os.HandlerThread.run(HandlerThread.java:61)

```

**Comment by kstoyanov5** [comment]
Hey @jhwsx , can you tell us what are the steps to reproduce it?

**Comment by jhwsx** [comment]
I'm sorry, but I don't remember, because it's a long story.

**Comment by pfmaggi** [comment]
Thanks for the update.
I'm going to close this, please open a new bug if you encounter the problem again.
