### ISSUE TITLE
Instrumentation Tests Fail

### ISSUE THREAD

**Issue by jaysondc** [android/plaid#780]
The instrumentation tests seem to be failing from a freshly cloned repo.

Running from the command line:

```
./gradlew connectedAndroidTest --no-parallel       

---------------------------

> Task :about:connectedDebugAndroidTest
The APKs have been extracted in the directory: /var/folders/fh/ps6w9_s53hq01479yxddtslw0000gn/T/apkSelect7988493008183905278
Starting 0 tests on Pixel 3 XL - 10
Tests on Pixel 3 XL - 10 failed: Instrumentation run failed due to 'Process crashed.'

com.android.builder.testing.ConnectedDevice > No tests found.[Pixel 3 XL - 10] FAILED 
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).

> Task :about:connectedDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':about:connectedDebugAndroidTest'.
> There were failing tests. See the report at: file:///Users/jayson.delacruz/Projects/Work/reference-projects/plaid/about/build/reports/androidTests/connected/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
289 actionable tasks: 1 executed, 288 up-to-date
```

Checking the log it's:

```
2019-10-24 15:15:53.238 15453-15453/io.plaidapp E/InstrumentationResultPrinter: Failed to mark test No Tests as finished after process crash
2019-10-24 15:15:53.241 15453-15453/io.plaidapp E/MonitoringInstr: Exception encountered by: null. Dumping thread state to outputs and pining for the fjords.
    android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f10002d
        at android.content.res.ResourcesImpl.getResourcePackageName(ResourcesImpl.java:284)
        at android.content.res.Resources.getResourcePackageName(Resources.java:2080)
        at com.google.android.gms.common.internal.StringResourceValueReader.<init>(Unknown Source:5)
        at com.google.firebase.FirebaseOptions.fromResource(com.google.firebase:firebase-common@@17.1.0:160)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.1.0:248)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@17.1.0:53)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2092)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2066)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@17.1.0:47)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2019-10-24 15:15:53.243 15453-15453/io.plaidapp E/THREAD_STATE:   Thread[HeapTaskDaemon,5,system]
    
      Thread[FinalizerWatchdogDaemon,5,system]
        java.lang.Object.wait(Native Method)
        java.lang.Object.wait(Object.java:442)
        java.lang.Object.wait(Object.java:568)
        java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:339)
        java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:319)
        java.lang.Daemons$Daemon.run(Daemons.java:137)
        java.lang.Thread.run(Thread.java:919)
    
      Thread[main,5,main]
        dalvik.system.VMStack.getThreadStackTrace(Native Method)
        java.lang.Thread.getStackTrace(Thread.java:1720)
        java.lang.Thread.getAllStackTraces(Thread.java:1796)
        androidx.test.runner.MonitoringInstrumentation.getThreadState(MonitoringInstrumentation.java:643)
        androidx.test.runner.MonitoringInstrumentation.dumpThreadStateToOutputs(MonitoringInstrumentation.java:638)
        androidx.test.runner.MonitoringInstrumentation.onException(MonitoringInstrumentation.java:632)
        androidx.test.runner.AndroidJUnitRunner.onException(AndroidJUnitRunner.java:523)
        android.app.ActivityThread.installProvider(ActivityThread.java:6985)
        android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
        android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
        android.app.ActivityThread.access$1300(ActivityThread.java:219)
        android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        android.os.Handler.dispatchMessage(Handler.java:107)
        android.os.Looper.loop(Looper.java:214)
        android.app.ActivityThread.main(ActivityThread.java:7356)
        java.lang.reflect.Method.invoke(Native Method)
        com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
    
      Thread[Jit thread pool worker thread 0,5,main]
    
      Thread[FinalizerDaemon,5,system]
        java.lang.Object.wait(Native Method)
        java.lang.Object.wait(Object.java:442)
        java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
        java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
        java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:271)
        java.lang.Daemons$Daemon.run(Daemons.java:137)
        java.lang.Thread.run(Thread.java:919)
    
      Thread[Signal Catcher,5,system]
    
      Thread[Profile Saver,5,system]
    
      Thread[Binder:15453_1,5,main]
    
      Thread[Binder:15453_3,5,main]
    
      Thread[ReferenceQueueDaemon,5,system]
        java.lang.Object.wait(Native Method)
        java.lang.Object.wait(Object.java:442)
        java.lang.Object.wait(Object.java:568)
        java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:215)
        java.lang.Daemons$Daemon.run(Daemons.java:137)
        java.lang.Thread.run(Thread.java:919)
    
      Thread[Binder:15453_2,5,main]
2019-10-24 15:15:53.243 15453-15453/io.plaidapp E/MonitoringInstr: Dying now...
2019-10-24 15:15:53.244 15453-15453/io.plaidapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.plaidapp, PID: 15453
    java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f10002d
        at android.app.ActivityThread.installProvider(ActivityThread.java:6988)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f10002d
        at android.content.res.ResourcesImpl.getResourcePackageName(ResourcesImpl.java:284)
        at android.content.res.Resources.getResourcePackageName(Resources.java:2080)
        at com.google.android.gms.common.internal.StringResourceValueReader.<init>(Unknown Source:5)
        at com.google.firebase.FirebaseOptions.fromResource(com.google.firebase:firebase-common@@17.1.0:160)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@17.1.0:248)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@17.1.0:53)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2092)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2066)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@17.1.0:47)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

I'm having the same issue in my own project that uses Dynamic Feature Modules. I even get similar runtime errors from the official App Bundle Sample repo: https://github.com/android/app-bundle-samples

**Comment by emartynov** [comment]
I would say it is issue with tooling probably.  However, I can not find any issue related in the Google tracker (https://issuetracker.google.com/issues/142043473)

**Comment by keyboardsurfer** [comment]
Can't verify with the latest master changes. Tracking over at the issuetracker.
